### ISSUE TITLE
H2 Aufgabe 4

### ISSUE THREAD

**Issue by AminLakhal** [AminLakhal/GIS-SoSe-2020#1]
Hey ich hatte Probleme die H2 von Charakte richtig anzeigen zu lassen.

**Comment by Plagiatus** [comment]
ja, das habe ich gemerkt. Das liegt in deinem Fall wahrscheinlich am `float:left`, mit dem sich alles nach links drückt wie es geht (dabei das umliegende div auf minimale Größe zusammenfällt), und weil der Text eben besser hoch passt. Außerdem ist der erste Block im `#Menu` div drin, was nicht wirklich Sinn macht. Eine mögliche Lösung dagegen dass #Menu (oder dann das neue div mit dem du das umschließt) so zusammenfällt ist es, diesem div `overflow: auto` zu geben, so nimmt es die richtige Höhe an und die Überschrift ist da wo sie hin sollte.

Weiteres Feedback zur Aufgabe:
- über 60 Errors und Warnings im W3V.
- Wenn du Code kopierst, dann machst du was falsch und es gibt (fast) immer eine bessere Lösung. In diesem Fall wäre es besser alles, was für eine Seitengröße gilt, als "Standard" festzusetzen und dann in den Media Queries nur das zu überschreiben, was sich ändert.
- Wo wir schon dabei sind: was ändert sich denn überhaupt in den unterschiedlichen Größen?

du stehst jetzt zwar auf Rot, aber das kannst du im Praktikum nochmal auf gelb-rot zurück verteidigen, noch bist du also nicht durchgefallen.
